print("JJJJJJJJJJJJJ   LLL       ")
print("JJJJJJJJJJJJJ   LLL       ")
print("     JJJ        LLL       ")
print("     JJJ        LLL       ")
print("     JJJ        LLL       ")
print(" JJ  JJJ        LLL       ")
print(" JJJ JJJ        LLLLLLLLLL")
print("  JJJJJ         LLLLLLLLLL")